#!/bin/bash
# This script needs distro bassed openrazer config and openrazer-daemon/meta to be installed
# This script needs razer-cli to be installed

mouseSerial=$(razer-cli -l | awk '/type: mouse/{flag=1} /serial:/&&flag{print $2; exit}')

# Capture the initial brightness value
initial_brightness=$(razer-cli -d "$mouseSerial" -l | grep "brightness:" | awk '{print $2}' | cut -d '.' -f1)

# Subtract 10 from the initial brightness value
new_brightness=$((initial_brightness - 20))

if [ "$new_brightness" -lt 0 ]; then
  new_brightness=0
fi

# Execute the command with the new brightness value
razer-cli -d "$mouseSerial" -b "$new_brightness"
