#!/bin/bash

update_dnf(){
	echo "Updating dnf packages...."
	sudo dnf update -y
}

update_flatpak(){
	echo "Updating flatpak packages......"
	sudo flatpak update -y
}

update_snap(){
	echo "Updating snap packages........"
	sudo snap refresh
}

if [ "$1" == "all" ]; then
	update_dnf
	update_flatpak
	update_snap
elif [ "$1" == "2" ]; then
	update_dnf
	update_flatpak
elif [ "$1" == "3" ]; then
	update_snap
	update_dnf
elif [ "$1" == "4" ]; then
	update_flatpak
	update_snap
else
	echo "Invalid argument. Usage:"
	echo " pudt all   - Update dnf, flatpak, and snap"
	echo " pudt 2     - Update dnf and flatpak"
	echo " pudt 3     - Update snap and dnf"
	echo " pudt 4     - Update flatpak and snap"
fi
